- id: core
  title: "CORE BANKING & LOANS"
  subtitle: "Core Banking Solutions"
  hero_title: "Empower Your Financial Services."
  hero_description: "Comprehensive banking solutions, flexible loan management, and secure transaction processing for modern financial institutions."
  hero_image: "/images/iaas-hero.svg"
  icon: '<svg class="h-6 w-6 mr-2" fill="currentColor" xmlns="http://www.w3.org/2000/svg" id="mdi-bank-transfer" viewBox="0 0 24 24"><path d="M15,14V11H18V9L22,12.5L18,16V14H15M14,7.7V9H2V7.7L8,4L14,7.7M7,10H9V15H7V10M3,10H5V15H3V10M13,10V12.5L11,14.3V10H13M9.1,16L8.5,16.5L10.2,18H2V16H9.1M17,15V18H14V20L10,16.5L14,13V15H17Z" /></svg>'
  sections:
    - title: "Comprehensive Banking Solutions"
      description: "Our core banking solutions offer robust and scalable services to meet the needs of modern financial institutions. Ensure efficient and secure transaction processing with our advanced banking platform."
      image_id: 1
      image_position: right
    - title: "Flexible Loan Management"
      description: "Manage loans efficiently with our flexible loan management system. Our platform supports various loan types and configurations, ensuring seamless loan processing and management tailored to your financial institution's needs."
      image_id: 2
      image_position: left
    - title: "Secure Transaction Processing"
      description: "Our secure transaction processing services ensure the safety and integrity of your financial transactions. Leverage our advanced security measures to protect your clients' data and maintain trust in your financial services."
      image_id: 3
      image_position: right
    - title: "Advanced Analytics"
      description: "Utilize our advanced analytics tools to gain insights into your financial operations. Our platform provides comprehensive data analysis and reporting capabilities to help you make informed decisions and drive growth."
      image_id: 4
      image_position: left
    - title: "Customer Relationship Management"
      description: "Enhance your customer relationships with our integrated CRM solutions. Our platform helps you manage customer interactions, track customer data, and improve customer satisfaction and loyalty."
      image_id: 5
      image_position: right
    - title: "Regulatory Compliance"
      description: "Ensure compliance with industry regulations and standards with our comprehensive compliance management tools. Our platform helps you stay up-to-date with regulatory requirements and maintain compliance effortlessly."
      image_id: 6
      image_position: left

- id: accounting
  title: "BLOCKCHAIN ACCOUNTING"
  subtitle: "Blockchain Accounting System"
  hero_title: "Empower Your Business with Blockchain."
  hero_description: "Access a wide range of blockchain solutions provided by trusted vendors, all managed and supported by our expert team."
  hero_image: "/images/saas-hero.svg"
  icon: '<svg class="h-6 w-6 mr-2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" color="currentColor"><path d="M5.5 10C5.62215 10 5.73571 9.94347 5.96282 9.83041L7.78832 8.92162C8.59611 8.51948 9 8.31841 9 8V4M5.5 10C5.37785 10 5.26429 9.94347 5.03718 9.83041L3.21168 8.92162C2.4039 8.51948 2 8.31841 2 8V4M5.5 10V6M9 4C9 3.68159 8.59611 3.48052 7.78832 3.07838L5.96282 2.16959C5.73571 2.05653 5.62215 2 5.5 2C5.37785 2 5.26429 2.05653 5.03718 2.16959L3.21168 3.07838C2.40389 3.48052 2 3.68159 2 4M9 4C9 4.31841 8.59611 4.51948 7.78832 4.92162L5.96282 5.83041C5.73571 5.94347 5.62215 6 5.5 6M2 4C2 4.31841 2.40389 4.51948 3.21168 4.92162L5.03718 5.83041C5.26429 5.94347 5.37785 6 5.5 6" stroke="currentColor"></path><path d="M18.5 10C18.6222 10 18.7357 9.94347 18.9628 9.83041L20.7883 8.92162C21.5961 8.51948 22 8.31841 22 8V4M18.5 10C18.3778 10 18.2643 9.94347 18.0372 9.83041L16.2117 8.92162C15.4039 8.51948 15 8.31841 15 8V4M18.5 10V6M22 4C22 3.68159 21.5961 3.48052 20.7883 3.07838L18.9628 2.16959C18.7357 2.05653 18.6222 2 18.5 2C18.3778 2 18.2643 2.05653 18.0372 2.16959L16.2117 3.07838C15.4039 3.48052 15 3.68159 15 4M22 4C22 4.31841 21.5961 4.51948 20.7883 4.92162L18.9628 5.83041C18.7357 5.94347 18.6222 6 18.5 6M15 4C15 4.31841 15.4039 4.51948 16.2117 4.92162L18.0372 5.83041C18.2643 5.94347 18.3778 6 18.5 6" stroke="currentColor"></path><path d="M11.5 6H12.5" stroke="currentColor"></path><path d="M2 12V15.5C2 16.9045 2 17.6067 2.33706 18.1111C2.48298 18.3295 2.67048 18.517 2.88886 18.6629C3.39331 19 4.09554 19 5.5 19" stroke="currentColor"></path><path d="M22 12V15.5C22 16.9045 22 17.6067 21.6629 18.1111C21.517 18.3295 21.3295 18.517 21.1111 18.6629C20.6067 19 19.9045 19 18.5 19" stroke="currentColor"></path><path d="M12 22C12.1222 22 12.2357 21.9435 12.4628 21.8304L14.2883 20.9216C15.0961 20.5195 15.5 20.3184 15.5 20V16M12 22C11.8778 22 11.7643 21.9435 11.5372 21.8304L9.71168 20.9216C8.9039 20.5195 8.5 20.3184 8.5 20V16M12 22V18M15.5 16C15.5 15.6816 15.0961 15.4805 14.2883 15.0784L12.4628 14.1696C12.2357 14.0565 12.1222 14 12 14C11.8778 14 11.7643 14.0565 11.5372 14.1696L9.71168 15.0784C8.90389 15.4805 8.5 15.6816 8.5 16M15.5 16C15.5 16.3184 15.0961 16.5195 14.2883 16.9216L12.4628 17.8304C12.2357 17.9435 12.1222 18 12 18M8.5 16C8.5 16.3184 8.90389 16.5195 9.71168 16.9216L11.5372 17.8304C11.7643 17.9435 11.8778 18 12 18" stroke="currentColor"></path></svg>'
  sections:
    - title: "Third-Party Blockchain Solutions"
      description: "Coderic Fintech also offers third-party blockchain solutions. Clients can access a wide range of blockchain solutions provided by trusted third-party vendors, all managed and supported by Coderic Fintech."
      image_id: 1
      image_position: right
    - title: "Scalability"
      description: "Our blockchain solutions are designed to scale with your business. Whether you need to add more users, increase storage, or enhance functionality, Coderic Fintech makes it easy to scale your blockchain environment as your business grows."
      image_id: 2
      image_position: left
    - title: "Shared Blockchain Platforms"
      description: "Coderic Fintech offers access to shared blockchain platforms where multiple clients can use the same blockchain environment. This is a cost-effective solution for businesses looking to leverage powerful blockchain technology without the need for dedicated resources."
      image_id: 3
      image_position: right
    - title: "Dedicated Blockchain Platforms"
      description: "For clients with specific needs, Coderic Fintech provides dedicated blockchain platforms. This ensures that the blockchain environment is tailored to the client's requirements, offering enhanced performance and security."
      image_id: 4
      image_position: left
    - title: "Security"
      description: "Security is a top priority at Coderic Fintech. Our blockchain offerings include robust security measures to protect your data and ensure compliance with industry standards."
      image_id: 5
      image_position: right
    - title: "Support"
      description: "Coderic Fintech provides comprehensive support for all our blockchain solutions. Our team of experts is available to assist with any issues or questions, ensuring that your blockchain environment runs smoothly."
      image_id: 6
      image_position: left

- id: risks
  title: "RISK MANAGEMENT SYSTEM"
  subtitle: "Risk Management"
  hero_title: "Improve Your Risk Management."
  hero_description: "Identification, evaluation, and mitigation of risks to protect your organization."
  hero_image: "/images/paas-hero.svg"
  icon: '<svg class="h-6 w-6 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path fill="none" stroke="currentColor" stroke-width="2" d="M14,10 L15,10 L15,9 L14,9 L14,10 Z M18,10 L19,10 L19,9 L18,9 L18,10 Z M18,6 L19,6 L19,5 L18,5 L18,6 Z M14,6 L15,6 L15,5 L14,5 L14,6 Z M9,19 L10,19 L10,18 L9,18 L9,19 Z M5,15 L6,15 L6,14 L5,14 L5,15 Z M10,10 L1,10 L1,23 L14,23 L14,14 M10,14 L23,14 L23,1 L10,1 L10,14 Z"/></svg>'
  sections:
    - title: "Risk Identification"
      description: "We offer services to identify potential risks in your organization, using advanced methodologies and specialized tools."
      image_id: 1
      image_position: right
    - title: "Risk Evaluation"
      description: "Our system allows evaluating identified risks, determining their impact and probability to prioritize mitigation actions."
      image_id: 2
      image_position: left
    - title: "Risk Mitigation"
      description: "We develop effective strategies to mitigate risks, ensuring the continuity and security of your operations."
      image_id: 3
      image_position: right
    - title: "Continuous Monitoring"
      description: "We implement continuous monitoring systems to detect and respond to new risks in a timely manner."
      image_id: 4
      image_position: left
    - title: "Regulatory Compliance"
      description: "Our services ensure that your organization complies with all applicable regulations and standards, reducing legal and financial risks."
      image_id: 5
      image_position: right
    - title: "Support"
      description: "We provide comprehensive support for all our risk management solutions. Our team of experts is available to assist with any issues or questions, ensuring that your operations run smoothly and efficiently."
      image_id: 6
      image_position: left

- id: fmi
  title: "FINANCIAL MARKET INFRASTRUCTURE"
  subtitle: "Financial Market Infrastructure"
  hero_title: "Transform Your Financial Market Infrastructure."
  hero_description: "Comprehensive solutions for payment systems, securities settlement, trade repositories, and central counterparties designed for modern financial markets."
  hero_image: "/images/iaas-hero.svg"
  icon: '<svg class="h-6 w-6 mr-2" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M44 11C44 9.34315 42.6569 8 41 8H7C5.34315 8 4 9.34315 4 11V20H44V11Z" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M4.1123 39.0301L16.2879 26.7293L22.8672 33.0301L30.9105 26L35.391 30.368" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M44 18V37C44 38.6569 42.6569 40 41 40H12" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M19.1118 14H37.1118" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M11.1108 14H13.1108" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M4 18V27" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'
  sections:
    - title: "Payment Systems"
      description: "Robust and efficient payment systems that facilitate secure and rapid financial transactions between institutions. Our solutions ensure reliability and compliance with international standards."
      image_id: 1
      image_position: right
    - title: "Securities Settlement Systems"
      description: "Advanced platforms for securities settlement that ensure secure transfer of ownership and efficient management of financial assets in real-time."
      image_id: 2
      image_position: left
    - title: "Central Securities Depositories"
      description: "Comprehensive infrastructure for centralized custody and administration of securities, ensuring integrity and transparency in all transactions."
      image_id: 3
      image_position: right
    - title: "Central Counterparties (CCPs)"
      description: "Solutions for central counterparties that manage counterparty risk in financial transactions, providing stability and security to markets."
      image_id: 4
      image_position: left
    - title: "Trade Repositories"
      description: "Centralized systems for collecting and maintaining records of derivatives and other financial transactions, ensuring transparency and regulatory compliance."
      image_id: 5
      image_position: right
    - title: "Interoperability and Integration"
      description: "Our FMI solutions are designed to integrate seamlessly with existing systems, ensuring smooth interoperability between different financial market infrastructures."
      image_id: 6
      image_position: left

- id: compliance
  title: "REGULATORY COMPLIANCE"
  subtitle: "Regulatory Compliance Solutions"
  hero_title: "Ensure Regulatory Compliance."
  hero_description: "Comprehensive compliance management systems, real-time monitoring, and automated reporting to meet all regulatory requirements in the financial sector."
  hero_image: "/images/iaas-hero.svg"
  icon: '<svg class="h-6 w-6 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path fill="none" stroke="currentColor" stroke-width="2" d="M8,6 L16,6 L16,1 L8,1 L8,6 L8,6 L8,6 Z M16,3 L21,3 L21,23 L3,23 L3,3 L8,3 M8,14 L11,17 L17,11"/></svg>'
  sections:
    - title: "Regulatory Compliance Management"
      description: "Comprehensive tools to manage and ensure compliance with financial regulations including KYC, AML, GDPR, and industry-specific requirements. Our platform keeps you updated with changing regulations."
      image_id: 1
      image_position: right
    - title: "Real-Time Monitoring and Alerts"
      description: "Advanced monitoring systems that track compliance metrics in real-time, providing instant alerts for potential violations or suspicious activities, enabling proactive risk management."
      image_id: 2
      image_position: left
    - title: "Automated Reporting"
      description: "Streamline regulatory reporting with our automated systems that generate accurate reports for regulatory bodies, reducing manual work and ensuring timely submission of all required documentation."
      image_id: 3
      image_position: right
    - title: "Audit Trail and Documentation"
      description: "Maintain comprehensive audit trails and documentation of all compliance activities. Our system ensures complete transparency and traceability for regulatory inspections and audits."
      image_id: 4
      image_position: left
    - title: "Policy Management"
      description: "Centralized management of compliance policies and procedures. Ensure all stakeholders have access to the latest policies and track acknowledgment and adherence across your organization."
      image_id: 5
      image_position: right
    - title: "Training and Certification"
      description: "Integrated training management system to ensure all staff members are properly trained on compliance requirements, with certification tracking and automated renewal reminders."
      image_id: 6
      image_position: left
